### ISSUE TITLE
Add validation checks to EMLeditor

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/EMLeditor#32]
People want some way to check their EML (beyond write_readme). DPchecker has functions to perform many of these checks, but this will require people running multiple independent functions. DPchecker has a wrapper function that runs ALL DPchecker functions at once, but many of them require access to the data files in addition to the metadata and would fail when only checking metadata.

Write a wrapper function for EMLeditor that runs just the EML-specific functions from DPchecker.

**Comment by wright13** [comment]
I think this will be pretty easy to do. The DPchecker fxn that runs all checks already has them internally grouped by metadata-only vs metadata + data files. I could add a "metadata_only" argument that just skips the data file checks, and then the wrapper fxn in EMLeditor can just call run_congruence_checks(metadata_only = TRUE)

**Comment by RobLBaker** [comment]
Cool - that's slicker than what I was going to implement (wrapper in EMLeditor that calls each metadata-only function from DPchecker). Do you want to add that component to DPchecker and I can add the wrapper function to EMLeditor?

**Comment by RobLBaker** [comment]
Done! See check_eml() function in check_eml.R
