### ISSUE TITLE
Set_nps_publisher function

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/EMLeditor#35]
Is this really worth doing? 

I'm getting a lot of mixed messaging from users. On the one hand, people don't seem to like the idea of an automated pipeline. The less work they have to do, the better. On the other hand, under the current implimentation some things are automatically handled in the background (like setting the publisher) and that has raised eyebrows and feedback has not been 100% positive: it seems people also want control over what is being done to the metadata. 

Unfortunately, for most NPS data publications the publisher is defined as Fort Collins and there are a lot of specific fields to set for the publisher. Giving people control over this will inevitably result in critical errors such as mismatches between the publisher and the ROR ID (will people even know what that is?) that will get passed up to DataCite, data.gov, etc. The solution appears to be to write a manual function with no options that gives people control over when they set the publisher and allows them to manually set the publisher (but no control over what the publisher is set to).

1) Remove .set_publisher from the utils file.
2) Remove calls to .set publisher from within set_ functions; remove NPS=TRUE from function arguments.
3) Write a set_NPSpublisher function that must be manually run and will correctly set the publisher.
4) set_NPSpublisher will have no options so that the publisher info is correctly specified.
5) set_NPSpublisher documentation will point people to set_publisher for full manual control over all fields in case they really. don't want to have NPS be the publisher.
6) This will likely mean having to re-think how the "by or for NPS" fields are generated.

**Comment by wright13** [comment]
Looking at the existing code, I'm not sure it's necessary to create a separate set_NPSpublisher fxn. It looks to me like you could just remove the .set_publisher calls so that it doesn't happen in functions that the user doesn't expect to alter publisher info. Then just expect users to call set_publisher() with the default args if they want NPS to be set as the publisher. If the user tries to specify non-default information when org_name == NPS you could throw a warning or an error. Does that make sense?

**Comment by RobLBaker** [comment]
Yes, definitely makes sense. Still not 100% sure this is worth doing though: it will create more work for users, which is one of the biggest things we are trying to avoid. It might increase user confidence in the tools. But it might not.
