### ISSUE TITLE
Intellectual Rights/ License

### ISSUE THREAD

**Issue by RobLBaker** [nationalparkservice/EMLeditor#46]
set_int_rights() to add appropriate text to eml/dataset/licensed/licenseName.
(url and identifier optional)

@juddpatterson  what should that text be?
-CC0
-public
-restricted

**Comment by RobLBaker** [comment]
So what should that text be?
-CC0
-public
-restricted

**Comment by juddpatterson** [comment]
I looked at the documentation from the DOI EDI group and they mention these three. I think these should work for us too. What do you think?

1. CC0 1.0 Universal
2. Public Domain
3. No License/Controlled Unclassified Information

**Comment by RobLBaker** [comment]
Works for me! I'll work on this as soon as I sort out the set_content_units issues.
