### ISSUE TITLE
write_readme function

### ISSUE THREAD

**Issue by krsherrill** [nationalparkservice/EMLeditor#54]
The 'write_readme' function appears to have a bug.  When I export the readme .txt file I'm getting a note that the CUI and Park Unit Content has not been defined.  I believe both these attributes are defined in the xml being summarized in the readme.txt so am puzzled why this warning is appearing.

Warning messages:
1: In get_content_units(eml_object) :
  No Park Unit Connections specified. Use the set_content_units() function to add Park Unit Connections.
2: In get_cui(eml_object) :
  CUI not properly specified. User set_cui to update the CUI code.

Here's a link to the EML being summarized in the readme.txt
https://doimspp-my.sharepoint.com/:u:/g/personal/ksherrill_nps_gov/EYjafZEDKQhLpuxJnUnGUvIBK_USRWVOovGZozbjEAR4Kw

**Comment by RobLBaker** [comment]
Oof.  Ok, I'll see if I can get this one up and working again. Thanks for the heads up!

**Comment by RobLBaker** [comment]
I think write_readme() should be working properly now. Thanks for the extra testing file! Let me know if it's not working as you expect/would like.
